name: 3. Official Release Tag

on:
  push:
    tags:
      - 'v*' # Chạy khi có tag bắt đầu bằng v (vd: v1.0, v2.1)

jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Cấu hình AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Login ECR (Lấy Registry URL)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build & Push Backend
      # Tag theo tên release (vd: v1.0) VÀ tag 'latest'
      - name: Build & Push Release Version (Backend)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/resume/backend:${{ github.ref_name }}
            ${{ steps.login-ecr.outputs.registry }}/resume/backend:latest

      # 4. Build & Push Frontend
      - name: Build & Push Frontend Release
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/resume/frontend:${{ github.ref_name }}
            ${{ steps.login-ecr.outputs.registry }}/resume/frontend:latest
